datasources:
 datasource:
  -
   name: "Solution-03-DS-01"
   description:
   jndiName: "jdbc/WSO2CarbonDB"
   properties:
     url: "jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000"
     username: wso2carbon
     password: wso2carbon
     driverClassName: "org.h2.Driver"
     maxActive: 50
     maxWait: 60000
     testOnBorrow: true
     validationQuery: "SELECT 1"
     validationInterval: 30000
     defaultAutoCommit: false