solutionConfig:
  executionSteps:
    -
      enable: true
      path: "identity-server/federation/carbon.super/service-providers/sample1.yaml"
    -
      enable: true
      path: "identity-server/default/carbon.super/identity-providers/sample1.yaml"
    -
      enable : true
      path: "identity-server/default/carbon.super/service-providers/sample1.yaml"
    -
      enable: true
      path: "tomcat/default/webapps/travelocity.com"
  deployerDependencies:
    -
      deployer: "tomcat/default/webapps/travelocity.com"
      dependency: "identity-server/default/carbon.super/service-providers/sample1.yaml"
