solutionConfig:
  executionSteps:
    -
      action: "install"
      path: "database-server/h2-database/database1"
    -
      action: "install"
      path: "database-server/h2-database/database2"
    -
      action: "install"
      path: "database-server/h2-database/database3"
    -
      action: "install"
      path: "identity-server/default/carbon.super/user-stores/facebook.yaml"
    -
      action: "install"
      path: "identity-server/default/carbon.super/user-stores/twitter.yaml"
    -
      action: "install"
      path: "identity-server/default/carbon.super/user-stores/google.yaml"
    -
      action: "install"
      path: "identity-server/default/carbon.super/identity-providers/twitter.yaml"
    -
      action: "install"
      path: "identity-server/default/carbon.super/identity-providers/facebook.yaml"
    -
      action: "install"
      path: "identity-server/default/carbon.super/identity-providers/google.yaml"
    -
      action: "install"
      path: "identity-server/default/carbon.super/service-providers/sample-sp.yaml"
    -
      action: "install"
      path: "tomcat/default/webapps/travelocity.com"
  deployerDependencies:
    -
      deployer: "tomcat/default/webapps/travelocity.com"
      dependency: "identity-server/default/carbon.super/service-providers/sample-sp.yaml"
