serverConfig:
  identityServer:
    -
      instance: "default"
      host: "localhost"
      port: 9443
      trustore: "default-client-truststore.jks"
      userName: "admin"
      password: "admin"
  tomcat:
    -
      instance: "default"
      host: "localhost"
      port: 8080